# NumPy Opdrachten

In dit notebook vind je de volgende opdrachten:


- <a href="#np_opdracht1"> Opdracht 1</a> Maak deze opdracht ter voorbereiding op het college over NumPy.
- <a href="#np_opdracht2"> Opdracht 2</a> Hiermee gaan we in het college aan de slag.
- <a href="#np_opdracht3"> Opdracht 3</a> Hiermee gaan we in het college aan de slag.
- <a href="#np_opdracht4"> Opdracht 4</a> Deze opdracht is facultatief, voor als je meer uitdaging wilt.

<a id="np_opdracht1"></a>
## Opdracht 1 
**Maak deze opdracht ter voorbereiding op het college**

In [1]:
import numpy as np

- Maak een 1D array x aan met de cijfers 0 t/m 5

In [2]:
x = np.array([0, 1, 2, 3, 4, 5])

- Laat de vorm (grootte van de dimensies) van de array zien

In [3]:
x.shape

(6,)

- Hervorm de array x tot een 2D array (2, 3) 

In [4]:
x = x.reshape(2, 3)

- Wat is nu de vorm?


In [5]:
x.shape

(2, 3)

- Laat het datatype zien


In [6]:
x.dtype

dtype('int32')

- Sla een kopie van de array op in y


In [7]:
y = x.copy()

- Maak een transpose van x



In [24]:
x = x.transpose()

- Maak een transpose van y


In [25]:
y = y.transpose()

- Vermenigvuldig alle waarden van y met 2


In [26]:
np.multiply(y, 2)

array([[ 0,  6],
       [ 2,  8],
       [ 4, 10]])

- Concateneer de twee arrays in een nieuwe array `z`


In [30]:
z = np.concatenate([x, y])
z

array([[0, 3],
       [1, 4],
       [2, 5],
       [0, 3],
       [1, 4],
       [2, 5]])

- Geef het gemiddelde, modus, mediaan en de standaarddeviatie van z


In [39]:
np.mean(z)

2.5

In [50]:
# modus nog berekenen

[0 2 4 1 3 5]


In [42]:
np.median(z)

2.5

In [43]:
np.std(z)

1.707825127659933

<a id="np_opdracht2"></a>
## Opdracht 2
**Python list vs. NumPy**

- Maak een list `lst` met 1.000.001 willekeurige getallen tussen 0 en 10 (gebruik `random.randint(0, 10)`)
- Bepaal de mediaan
- Maak een list met daarin het kwadraat van elk element in `lst`
- Maak een list met daarin alleen alle even getallen uit `lst`
- Maak een tweede list `lst2` met 1.000.001 willekeurige getallen
- Maak een list met daarin de som van de elementen uit `lst` en `lst2`, dus:
  - `lst_samen[0] = lst[0] + lst2[0]`,
  - `lst_samen[1] = lst[1] + lst2[1]`,
  - etc.

- Doe bovenstaande ook met Numpy

- Gebruik `%timeit` voor je code om de snelheid te vergelijken

In [8]:
import math
import random
import numpy as np

In [25]:
list = []
for i in range(1000001):
    list.append(random.randint(0, 10))

In [26]:
mid = len(list) / 2
if mid % 1 == 0:
    mid = int(mid)
    mediaan = (list[mid - 1] + list[mid]) / 2
else:
    mid = int(mid - 0.5)
    mediaan = list[mid]

In [33]:
list_squared = []
for i in list:
    list_squared.append(i ** 2)

In [36]:
list_even = []
for i in list:
    if i % 2 == 0:
        list_even.append(i)

In [37]:
list2 = []
for i in range(1000001):
    list2.append(random.randint(0, 10))

In [42]:
list_add = []
for i in list:
    list_add.append(list[i] + list2[i])

Hieronder volgt met numpy

In [71]:
arr = np.random.choice(np.arange(0, 10), size = (1, 1000001))

In [72]:
median = np.median(arr)

In [73]:
arr_squared = np.square(arr)

In [74]:
arr_even = arr[arr % 2 == 0]

In [79]:
arr2 = np.random.choice(np.arange(0, 10), size = (1, 1000001))

In [80]:
arr_add = arr + arr2

<a id="np_opdracht3"></a>
## Opdracht 3

De blokcoördinator D.O. Cent van blok A  wil graag de cijfers analyseren en verwerken. Het blok bestaat uit 3 vakken, die door 10 studenten gevolgd zijn. Analyse omvat o.a. het bepalen van gemiddelde cijfer, het aantal voldoendes en cursusrendement. De verwerking bestaat uit het corrigeren van de cijfers.

In `blokAcijfers.txt` staan de cijfers per vak (naast elkaar staan de vakken, onder elkaar de studenten):

vak1 | vak2 | vak3
----|-------|------
6.5 | 7.3   | 6.4
8.0 | 8.0	| 8.5
3.2	| 4.0	| 5.0
7.9	| 7.1	| 3.5
7.3	| 7.8	| 8.0
8.6	| 8.0	| 9.0
4.0	| 6.0	| 5.5
7.3	| 7.8	| 7.8
4.5	| 5.6	| 7.7
5.0	| 7.0	| 7.2


In [1]:
import numpy as np

Start met de data verzamelen:
- Lees tekstbestand: blokAcijfers.txt in met `np.loadtxt`, sla de data op in een numpy array met naam `vCijfers`.
- Laat zien dat de gegevens goed ingelezen zijn.
- Toon de array attributen.

In [44]:
vCijfers = np.loadtxt("blokAcijfers.txt")

De docent ziet dat er 2 cijfers fout zijn en wil deze corrigeren
-	Wijzig de volgende cijfers:
    *	vak-2, student-3  cijfer 4.0 moet 4.3 worden.
    *	vak-1, student-10, cijfer 5.0 moet 4.8 worden.

In [13]:
vCijfers[2, 1] = 4.3
vCijfers[9, 0] = 4.8

De docent wil wat basisgegevens weten.
-	Bepaal minimum, maximum en gemiddelde van alle cijfers.
-	Bepaal minimum, maximum en gemiddelde van elk vak (3 getallen).
-	Bepaal minimum, maximum en gemiddelde van elke student (10 getallen).

minimum, maximum en gemiddelde van alle cijfers

In [20]:
vCijfers.min()
vCijfers.max()
vCijfers.mean()

np.float64(6.653333333333333)

In [28]:
# vak a
vCijfers[:, 0].min().round(2)
vCijfers[:, 0].max().round(2)
vCijfers[:, 0].mean().round(2)

# vak b
vCijfers[:, 1].min().round(2)
vCijfers[:, 1].max().round(2)
vCijfers[:, 1].mean().round(2)

# vak c
vCijfers[:, 2].min().round(2)
vCijfers[:, 2].max().round(2)
vCijfers[:, 2].mean().round(2)

np.float64(6.86)

In [34]:
for i in range(0, 10):
    vCijfers[i].min()
    vCijfers[i].max()
    vCijfers[i].mean()

De docent wil graag zien wat de cijfers zijn als ze afgerond worden op hele getallen.
-	Kopieer de array naar een nieuwe array.
-	Rond de waarden af.
-	Laat de resultaten zien.

In [45]:
vCijfers_rond = vCijfers.copy()

Er is een fout gemaakt bij de cijfers van het 1e vak. Iedere student krijgt 0.5 punt extra erbij.
-	Vul een ‘ophoogarray’ bestaande uit 3 kolommen en elk 10 rijen en vul deze eerst met 0.0 en daarna de eerste rij met de waarden 0.5.
-	Tel de ophoogarray op bij de cijfer array.

In [47]:
ophoogarray = np.zeros((10, 3), float)
ophoogarray += 0.5
vCijfers += ophoogarray
vCijfers

array([[7. , 7.8, 6.9],
       [8.5, 8.5, 9. ],
       [3.7, 4.5, 5.5],
       [8.4, 7.6, 4. ],
       [7.8, 8.3, 8.5],
       [9.1, 8.5, 9.5],
       [4.5, 6.5, 6. ],
       [7.8, 8.3, 8.3],
       [5. , 6.1, 8.2],
       [5.5, 7.5, 7.7]])

De docent wil een lijstje waarin hij in één opslag ziet waar een voldoende (`True`) en waar een onvoldoende (`False`) staat.  
-	Maakt dit lijstje.

In [49]:
voldoende = vCijfers >= 5.5
voldoende

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

<a id="np_opdracht4"></a>
## Opdracht 4
**Deze opdracht is facultatief**

In [ ]:
import numpy as np

#### 3. Create a null vector of size 10

#### 6.  Create a null vector of size 10 but the fifth value which is 1

#### 8.  Reverse a vector with values ranging from 10 to 49 (first element becomes last)

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### 11. Create a 3x3 identity matrix

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

#### 15. Create a 2d array with 1 on the border and 0 inside

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

#### 29. How to round away from zero a float array ?

#### 30. How to find common values between two arrays?

#### 36. Extract the integer part of a random array using 5 different methods

In [ ]:
Z = np.random.uniform(0,10,10)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

#### 40. Create a random vector of size 10 and sort it

#### 42. Consider two random array A and B, check if they are equal

#### 45. Create random vector of size 10 and replace the maximum value by 0

#### 50. How to find the closest value (to a given scalar) in a vector?

In [ ]:
v = np.random.uniform(0,100)

#### 52. Consider a random vector with shape (10,2) representing coordinates, find point by point distances

In [ ]:
Z = np.random.random((10,2))


#### 57. How to randomly place p elements in a 2D array?

#### 58. Subtract the mean of each row of a matrix

#### 59. How to sort an array by the nth column?

#### 60. How to tell if a given 2D array has null columns?

#### 61. Find the nearest value from a given value in an array

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### 72. How to swap two rows of an array?

#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 83. How to find the most frequent value in an array?

#### 89. How to get the n largest values of an array